config {
  // Task 4: Materializing the model as 'incremental'
  type: "incremental",
  
  bigquery: {
    // Task 4: Configuring 'partitionBy' 
    partitionBy: "TIMESTAMP_TRUNC(start_time, DAY)",
    
    // Task 4: Configuring 'clusterBy' 
    clusterBy: ["start_station_name", "subscriber_type"]
  }
}

SELECT 
  -- Task 3 Implementation: Using the generate_surrogate_key function
  ${functions.generate_surrogate_key(['trip_id', 'start_time'])} AS trip_surrogate_key,
  
  -- Task 3 Implementation: Using the minutes_to_hours function
  ${functions.minutes_to_hours('duration_minutes')} AS duration_hours,
  
  -- Selecting the rest of the raw columns needed
  * FROM 
  ${ref("bikeshare_trips")}
WHERE
  -- Task 2 Implementation: Dynamic filter for CI/CD Test Mode
  ${ dataform.projectConfig.vars.is_test_run === "true" ? 
     "start_time >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)" : 
     "true" 
   }

  -- Task 4 Implementation: Standard incremental logic to only pull new records
  ${when(incremental(), `AND start_time > (SELECT MAX(start_time) FROM ${self()})`)}