config {
    type: "incremental", 
    /*schema: "dataform",*/
    description: "incremental staging table for Trips",
    bigquery: {
        partitionBy: "TIMESTAMP_TRUNC(start_time, DAY)",
        clusterBy: ["start_station_name", "subscriber_type"]    
        },
    assertions: {
        rowConditions: [
          "end_time >= start_time",
          "subscriber_type is not null",
          "coalesce(duration_minutes,0) > 0"
        ]
      }
    }

SELECT
  trip_id,
  subscriber_type,
  bikeid,
  start_station_id,
  start_station_name,
  end_station_id,
  end_station_name,
  start_time,
  -- Task 3: Calling our custom JS functions
  ${functions.generate_surrogate_key(["trip_id", "start_time"])} AS trip_surrogate_key, /* include start_time in case trip_id is recycled*/
  ${functions.minutes_to_hours("duration_minutes")} AS duration_hours
FROM
  ${ref("bikeshare_trips")}
WHERE 1=1
  
  -- Task 2: CI/CD Test Mode Variable
  -- If 'is_test_run' is true, only grab the last 7 days of data.
  ${when(dataform.projectConfig.vars.is_test_run === "true", 
    `AND start_time >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)`
  )}
    
  -- Task 4: Incremental Logic
  -- This only compiles if the table already exists in BigQuery.
  -- It tells Dataform to only grab rows newer than the max date currently in the table.
  ${when(incremental(), 
    `AND start_time > (SELECT MAX(start_time) FROM ${self()})`
  )}