config {
  type: "view", // This ensures it doesn't duplicate storage!
  dependencies: [
    "assert_unique_stations", // Adding the dependencies from Task 6
    "assert_trips_quality"
  ],
  description: "Gold layer view joining trips and stations to calculate revenue.",
  columns: {
    trip_id: "The unique identifier for the trip.",
    start_station_id: "The ID of the starting station.",
    subscriber_type: "The user's subscription category.",
    duration_minutes: "The length of the trip in minutes.",
    estimated_revenue: "Revenue calculated at $0.12/min for Walk Up and $0.00 for Members."
  }
}

SELECT
  t.trip_id,
  s.start_station_id,
  t.subscriber_type,
  t.duration_minutes,
  
  -- Business Logic: Calculate 'estimated_revenue'
  CASE
    WHEN lower(t.subscriber_type) like '%walk up%' THEN t.trip_duration_minutes * 0.12
    WHEN lower(t.subscriber_type) like '%member%' THEN 0.00
    ELSE 0.00
  END AS estimated_revenue

FROM
  ${ref("stg_trips")} AS t
JOIN
  ${ref("bikeshare_stations")} AS s
ON
  t.start_station_id = s.station_id