defaultProject: sbx-edgar-ocado
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.42
defaultLocation: EU  # Change from US to EU

vars:
  is_test_run: "true"